"""remake table

Revision ID: f34ae3eb0447
Revises: f9a6dd0d1b86
Create Date: 2019-04-30 08:36:19.360571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34ae3eb0447'
down_revision = 'f9a6dd0d1b86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IP',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_IP_timestamp'), 'IP', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_IP_timestamp'), table_name='IP')
    op.drop_table('IP')
    # ### end Alembic commands ###
