"""empty message

Revision ID: f657c70537f2
Revises: c9991cc271cf
Create Date: 2019-04-13 15:51:50.347040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f657c70537f2'
down_revision = 'c9991cc271cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highscore', sa.Column('assists', sa.Float(), nullable=True))
    op.add_column('highscore', sa.Column('per', sa.Float(), nullable=True))
    op.add_column('highscore', sa.Column('picture_url', sa.String(), nullable=True))
    op.add_column('highscore', sa.Column('ppg', sa.Float(), nullable=True))
    op.add_column('highscore', sa.Column('rebounds', sa.Float(), nullable=True))
    op.drop_column('highscore', 'total')
    op.drop_column('highscore', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('highscore', sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('highscore', sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('highscore', 'rebounds')
    op.drop_column('highscore', 'ppg')
    op.drop_column('highscore', 'picture_url')
    op.drop_column('highscore', 'per')
    op.drop_column('highscore', 'assists')
    # ### end Alembic commands ###
